export const noteCategories = [
  "Art & Philosophy",
  "Robotics & Control",
  "Artificial Intelligence",
  "Signal Processing & IT",
] as const;
export type NoteCategory = (typeof noteCategories)[number];
export type NoteType = "Lecture notes" | "Cheatsheet" | "Thesis / Article";
export type Note = {
  title: string;
  file: string;
  category: NoteCategory;
  languages: string[];
  university: string;
  type: NoteType;
  authors: string[];
  year: number;
  draft?: boolean;
  handwritten?: boolean;
};
const davide = "Davide Lanza";
export const notes: Note[] = [
  {
    title: "Art and Design in the Digital Age",
    file: "lanza_edxdigitalart.pdf",
    year: 2020,
    category: "Art & Philosophy",
    languages: ["English"],
    university: "Shenkar College",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Neurosciences of Cognition and Perception",
    file: "lanza_ncpnotes.pdf",
    year: 2017,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Political Philosophy",
    file: "lanza_politicalphil.pdf",
    year: 2017,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Philosophy of Mind",
    file: "lanza_filomente.pdf",
    year: 2018,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Cheatsheet",
    authors: [davide],
    handwritten: true,
  },
  {
    title: "Heredity and Social Policies (term paper)",
    file: "lanza_cognitive_article.pdf",
    year: 2018,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Thesis / Article",
    authors: [davide],
  },
  {
    title: "Exploring Japanese Avant-Garde Art Through Butoh Dance",
    file: "lanza_butoh.pdf",
    year: 2019,
    category: "Art & Philosophy",
    languages: ["English"],
    university: "Keio University",
    type: "Lecture notes",
    authors: [davide],
    draft: true,
  },
  {
    title: "Visual Studies & Logic (Seminars)",
    file: "lanza_ianua_sum2018.pdf",
    year: 2018,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "IANUA Summer School",
    type: "Lecture notes",
    authors: [davide],
    draft: true,
  },
  {
    title: "Cultural Anthropology",
    file: "lanza_antro_draft.pdf",
    year: 2019,
    category: "Art & Philosophy",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
    draft: true,
  },
  {
    title: "System Theory",
    file: "lanza_grillo_systemtheory.pdf",
    year: 2017,
    category: "Robotics & Control",
    languages: ["English"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide, "Andrea Grillo"],
  },
  {
    title: "Classical Control",
    file: "lanza_claco.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Cheatsheet",
    authors: [davide],
    handwritten: true,
  },
  {
    title: "Control Theory",
    file: "lanza_controltheory.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Dynamic Model Based Control",
    file: "lanza_dybac.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Cheatsheet",
    authors: [davide],
    handwritten: true,
  },
  {
    title: "System Identification",
    file: "lanza_sysid.pdf",
    year: 2020,
    category: "Robotics & Control",
    languages: ["English"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Ambient Intelligence",
    file: "lanza_ambint.pdf",
    year: 2020,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Computer Vision",
    file: "lanza_covis.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Lecture notes",
    authors: [davide],
    draft: true,
  },
  {
    title: "Optimization Techniques",
    file: "lanza_optec.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Lecture notes",
    authors: [davide],
    handwritten: true,
  },
  {
    title: "Mechanics of Mechanisms and Machines",
    file: "lanza_mmm_partial.pdf",
    year: 2020,
    category: "Robotics & Control",
    languages: ["English"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
    draft: true,
  },
  {
    title: "Introduction to ROS",
    file: "lanza_introros.pdf",
    year: 2019,
    category: "Robotics & Control",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Artificial Intelligence",
    file: "lanza_artin.pdf",
    year: 2019,
    category: "Artificial Intelligence",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Cheatsheet",
    authors: [davide],
    handwritten: true,
  },
  {
    title: "Machine Learning",
    file: "lanza_machlearn.pdf",
    year: 2020,
    category: "Artificial Intelligence",
    languages: ["English"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Stanford CS 221 · Artificial Intelligence",
    file: "stanford_cs221_artin.pdf",
    year: 2019,
    category: "Artificial Intelligence",
    languages: ["English"],
    university: "Stanford University",
    type: "Cheatsheet",
    authors: ["Afshine Amidi", "Shervine Amidi"],
  },
  {
    title: "Stanford CS 229 · Machine Learning",
    file: "stanford_cs229_machlearn.pdf",
    year: 2018,
    category: "Artificial Intelligence",
    languages: ["English"],
    university: "Stanford University",
    type: "Cheatsheet",
    authors: ["Afshine Amidi", "Shervine Amidi"],
  },
  {
    title: "Stanford CS 230 · Deep Learning",
    file: "stanford_cs230_deeplearn.pdf",
    year: 2018,
    category: "Artificial Intelligence",
    languages: ["English"],
    university: "Stanford University",
    type: "Cheatsheet",
    authors: ["Afshine Amidi", "Shervine Amidi"],
  },
  {
    title: "Signal Processing",
    file: "lanza_sipro.pdf",
    year: 2019,
    category: "Signal Processing & IT",
    languages: ["English"],
    university: "École Centrale de Nantes",
    type: "Cheatsheet",
    authors: [davide],
  },
  {
    title: "Signal Processing with MATLAB",
    file: "lanza_etsimatlab.pdf",
    year: 2018,
    category: "Signal Processing & IT",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
  {
    title: "Databases",
    file: "lanza_databases.pdf",
    year: 2018,
    category: "Signal Processing & IT",
    languages: ["Italian"],
    university: "University of Genoa",
    type: "Lecture notes",
    authors: [davide],
  },
];
